# -*- coding: utf-8 -*-
"""MARKET CODE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9ubd7iMUF7dKHTAMXwr4Y1ynsGVWQmX
"""

"""
Streamlit Market Intelligence Dashboard
========================================
Complete dashboard combining:
- Nifty 200 News with Sentiment Analysis
- Real-time Stock Prices (Alpha Vantage)
- Macroeconomic Indicators
- Price Reaction Analysis

Run with: streamlit run app.py

Author: Market Alert System
Date: 2025-11-07
"""

import streamlit as st
import feedparser
from transformers import pipeline
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from datetime import datetime, timedelta
import time
import requests
import json

# ===========================
# PAGE CONFIG
# ===========================
st.set_page_config(
    page_title="Market Intelligence Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ===========================
# CUSTOM CSS
# ===========================
st.markdown("""
    <style>
    .main {
        padding-top: 2rem;
    }
    .stAlert {
        padding: 1rem;
        border-radius: 0.5rem;
    }
    h1 {
        color: #1f77b4;
        padding-bottom: 1rem;
    }
    .metric-card {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 0.5rem;
        margin: 0.5rem 0;
    }
    </style>
""", unsafe_allow_html=True)

# ===========================
# ALPHA VANTAGE API CLASS
# ===========================
class AlphaVantageAPI:
    """Alpha Vantage API Client"""

    def __init__(self, api_key):
        self.api_key = api_key
        self.base_url = "https://www.alphavantage.co/query"
        self.last_request_time = 0

    def _rate_limit(self):
        """Rate limiting"""
        current_time = time.time()
        time_since_last = current_time - self.last_request_time
        if time_since_last < 12:
            time.sleep(12 - time_since_last)
        self.last_request_time = time.time()

    def _make_request(self, params):
        """Make API request"""
        self._rate_limit()
        params['apikey'] = self.api_key

        try:
            response = requests.get(self.base_url, params=params, timeout=30)
            response.raise_for_status()
            data = response.json()

            if "Error Message" in data or "Note" in data:
                return None

            return data
        except:
            return None

    def get_quote(self, symbol):
        """Get stock quote"""
        params = {'function': 'GLOBAL_QUOTE', 'symbol': symbol}
        data = self._make_request(params)

        if not data or 'Global Quote' not in data:
            return None

        quote = data['Global Quote']
        return {
            'symbol': quote.get('01. symbol', symbol),
            'price': float(quote.get('05. price', 0)),
            'change': float(quote.get('09. change', 0)),
            'change_percent': quote.get('10. change percent', '0%'),
            'volume': int(quote.get('06. volume', 0)),
            'latest_trading_day': quote.get('07. latest trading day', '')
        }

    def get_daily_data(self, symbol, days=30):
        """Get daily prices"""
        params = {'function': 'TIME_SERIES_DAILY', 'symbol': symbol, 'outputsize': 'compact'}
        data = self._make_request(params)

        if not data or 'Time Series (Daily)' not in data:
            return pd.DataFrame()

        records = []
        for date_str, values in data['Time Series (Daily)'].items():
            records.append({
                'date': pd.to_datetime(date_str),
                'open': float(values['1. open']),
                'high': float(values['2. high']),
                'low': float(values['3. low']),
                'close': float(values['4. close']),
                'volume': int(values['5. volume'])
            })

        df = pd.DataFrame(records)
        return df.sort_values('date').tail(days).reset_index(drop=True)

    def get_macro_data(self, indicator):
        """Get macro indicator"""
        params = {'function': indicator, 'interval': 'monthly'}
        data = self._make_request(params)

        if not data or 'data' not in data:
            return pd.DataFrame()

        records = []
        for entry in data['data']:
            if entry['value'] != '.':
                records.append({
                    'date': pd.to_datetime(entry['date']),
                    'value': float(entry['value'])
                })

        df = pd.DataFrame(records)
        return df.sort_values('date').reset_index(drop=True)

# ===========================
# CONFIGURATION
# ===========================
STOCK_SYMBOLS = {
    "Reliance Industries": "RELIANCE.BSE",
    "TCS": "TCS.NSE",
    "HDFC Bank": "HDFCBANK.NSE",
    "Infosys": "INFY.NSE",
    "ICICI Bank": "ICICIBANK.NSE",
    "Bharti Airtel": "BHARTIARTL.NSE",
    "ITC": "ITC.NSE",
    "State Bank of India": "SBIN.NSE",
    "Wipro": "WIPRO.NSE",
    "Tata Motors": "TATAMOTORS.NSE"
}

MACRO_INDICATORS = {
    "Federal Funds Rate": "FEDERAL_FUNDS_RATE",
    "Consumer Price Index": "CPI",
    "Real GDP": "REAL_GDP",
    "Unemployment Rate": "UNEMPLOYMENT"
}

NIFTY_200_STOCKS = [
    "Reliance", "TCS", "HDFC Bank", "Infosys", "ICICI Bank", "Bharti Airtel",
    "ITC", "State Bank", "SBI", "Hindustan Unilever", "Bajaj Finance"
]

# ===========================
# SESSION STATE
# ===========================
if 'news_articles' not in st.session_state:
    st.session_state.news_articles = []
if 'api_initialized' not in st.session_state:
    st.session_state.api_initialized = False

# ===========================
# SIDEBAR - API KEY INPUT
# ===========================
with st.sidebar:
    st.title("⚙️ Settings")

    st.markdown("### Alpha Vantage API Key")
    st.markdown("Get FREE key: [Alpha Vantage](https://www.alphavantage.co/support/#api-key)")

    api_key = st.text_input(
        "API Key",
        type="password",
        value=st.session_state.get('api_key', ''),
        help="Enter your Alpha Vantage API key"
    )

    if api_key:
        st.session_state.api_key = api_key
        st.session_state.api_initialized = True
        st.success("✅ API Key Set")
    else:
        st.warning("⚠️ Please enter API key to use stock features")

    st.markdown("---")

    st.markdown("### Features")
    st.markdown("""
    - 📰 News Sentiment Analysis
    - 📊 Real-time Stock Prices
    - 🌍 Macro Indicators
    - 📈 Price Charts
    """)

# ===========================
# LOAD SENTIMENT MODEL
# ===========================
@st.cache_resource
def load_sentiment_model():
    return pipeline("sentiment-analysis", model="yiyanghkust/finbert-tone")

try:
    finbert = load_sentiment_model()
except:
    finbert = None
    st.warning("⚠️ Sentiment model not loaded. Install transformers: pip install transformers torch")

# ===========================
# NEWS FUNCTIONS
# ===========================
def fetch_news(num_articles=10):
    """Fetch news from Google News"""
    all_articles = []

    for stock in NIFTY_200_STOCKS[:10]:
        try:
            url = f"https://news.google.com/rss/search?q={stock}+stock+india+when:2d&hl=en-IN&gl=IN&ceid=IN:en"
            feed = feedparser.parse(url)

            for entry in feed.entries[:2]:
                all_articles.append(entry)
                if len(all_articles) >= num_articles:
                    break
        except:
            continue

        if len(all_articles) >= num_articles:
            break

    return all_articles

def process_news(articles):
    """Process news with sentiment"""
    if not finbert:
        return []

    records = []
    for art in articles:
        title = art.title
        url = art.link

        try:
            sentiment_result = finbert(title[:512])[0]
            sentiment = sentiment_result["label"].lower()
            score = sentiment_result["score"]
        except:
            sentiment = "neutral"
            score = 0.5

        records.append({
            "Title": title,
            "Sentiment": sentiment,
            "Score": round(score, 2),
            "Link": url,
            "Published": getattr(art, 'published', 'Recent')
        })

    return records

# ===========================
# MAIN APP
# ===========================
st.title("📈 Market Intelligence Dashboard")
st.markdown("Real-time market data, news sentiment, and macroeconomic indicators")
st.markdown("---")

# ===========================
# TAB NAVIGATION
# ===========================
tab1, tab2, tab3, tab4 = st.tabs([
    "📰 News & Sentiment",
    "📊 Stock Prices",
    "🌍 Macro Indicators",
    "📈 Price Analysis"
])

# ===========================
# TAB 1: NEWS & SENTIMENT
# ===========================
with tab1:
    st.header("📰 Market News with Sentiment Analysis")

    col1, col2 = st.columns([1, 1])

    with col1:
        if st.button("🔄 Refresh News", type="primary", use_container_width=True):
            with st.spinner("Fetching latest news..."):
                articles = fetch_news(15)
                if articles and finbert:
                    st.session_state.news_articles = process_news(articles)
                    st.success(f"✅ Loaded {len(st.session_state.news_articles)} articles")
                    st.rerun()

    with col2:
        if st.button("🗑️ Clear News", use_container_width=True):
            st.session_state.news_articles = []
            st.rerun()

    # Load initial news
    if not st.session_state.news_articles and finbert:
        with st.spinner("Loading news..."):
            articles = fetch_news(15)
            st.session_state.news_articles = process_news(articles)

    # Display metrics
    if st.session_state.news_articles:
        df_news = pd.DataFrame(st.session_state.news_articles)

        col1, col2, col3, col4 = st.columns(4)

        with col1:
            st.metric("Total Articles", len(df_news))
        with col2:
            st.metric("🟢 Positive", len(df_news[df_news['Sentiment'] == 'positive']))
        with col3:
            st.metric("⚪ Neutral", len(df_news[df_news['Sentiment'] == 'neutral']))
        with col4:
            st.metric("🔴 Negative", len(df_news[df_news['Sentiment'] == 'negative']))

        st.markdown("---")

        # Sentiment chart
        sentiment_counts = df_news['Sentiment'].value_counts().reset_index()
        sentiment_counts.columns = ["Sentiment", "Count"]

        fig = px.bar(
            sentiment_counts,
            x="Sentiment",
            y="Count",
            color="Sentiment",
            color_discrete_map={"positive": "green", "neutral": "gray", "negative": "red"},
            title="Sentiment Distribution"
        )
        st.plotly_chart(fig, use_container_width=True)

        st.markdown("---")

        # News articles
        st.subheader("📰 Latest Articles")

        for article in st.session_state.news_articles:
            sentiment_emoji = {"positive": "🟢", "neutral": "⚪", "negative": "🔴"}

            st.markdown(f"**[{article['Title']}]({article['Link']})**")
            st.caption(f"{sentiment_emoji[article['Sentiment']]} {article['Sentiment'].upper()} (confidence: {article['Score']}) | {article.get('Published', 'Recent')}")
            st.markdown("---")
    else:
        st.info("👆 Click 'Refresh News' to load market news")

# ===========================
# TAB 2: STOCK PRICES
# ===========================
with tab2:
    st.header("📊 Real-time Stock Prices")

    if not st.session_state.api_initialized:
        st.warning("⚠️ Please enter your Alpha Vantage API key in the sidebar")
    else:
        api = AlphaVantageAPI(st.session_state.api_key)

        # Stock selector
        col1, col2 = st.columns([2, 1])

        with col1:
            selected_stock = st.selectbox(
                "Select Stock",
                options=list(STOCK_SYMBOLS.keys()),
                index=0
            )

        with col2:
            if st.button("📊 Get Quote", type="primary", use_container_width=True):
                st.rerun()

        # Get symbol
        symbol = STOCK_SYMBOLS[selected_stock]

        # Display quote
        with st.spinner(f"Fetching data for {selected_stock}..."):
            quote = api.get_quote(symbol)

            if quote:
                col1, col2, col3, col4 = st.columns(4)

                with col1:
                    st.metric("Price", f"₹{quote['price']:.2f}")
                with col2:
                    change_pct = float(quote['change_percent'].rstrip('%'))
                    st.metric("Change", f"{change_pct:+.2f}%", delta=f"₹{quote['change']:.2f}")
                with col3:
                    st.metric("Volume", f"{quote['volume']:,}")
                with col4:
                    st.metric("Trading Day", quote['latest_trading_day'])

                st.markdown("---")

                # Price chart
                st.subheader("📈 30-Day Price Chart")

                df_prices = api.get_daily_data(symbol, days=30)

                if not df_prices.empty:
                    fig = go.Figure()

                    fig.add_trace(go.Candlestick(
                        x=df_prices['date'],
                        open=df_prices['open'],
                        high=df_prices['high'],
                        low=df_prices['low'],
                        close=df_prices['close'],
                        name=symbol
                    ))

                    fig.update_layout(
                        title=f"{selected_stock} - Last 30 Days",
                        yaxis_title="Price (₹)",
                        xaxis_title="Date",
                        height=500,
                        xaxis_rangeslider_visible=False
                    )

                    st.plotly_chart(fig, use_container_width=True)

                    # Statistics
                    col1, col2, col3, col4 = st.columns(4)

                    with col1:
                        st.metric("30-Day High", f"₹{df_prices['high'].max():.2f}")
                    with col2:
                        st.metric("30-Day Low", f"₹{df_prices['low'].min():.2f}")
                    with col3:
                        first_price = df_prices.iloc[0]['close']
                        last_price = df_prices.iloc[-1]['close']
                        return_pct = ((last_price - first_price) / first_price) * 100
                        st.metric("30-Day Return", f"{return_pct:+.2f}%")
                    with col4:
                        st.metric("Avg Volume", f"{df_prices['volume'].mean():,.0f}")
                else:
                    st.warning("No price data available")
            else:
                st.error("❌ Failed to fetch stock data. Check API key or symbol.")

# ===========================
# TAB 3: MACRO INDICATORS
# ===========================
with tab3:
    st.header("🌍 Macroeconomic Indicators")

    if not st.session_state.api_initialized:
        st.warning("⚠️ Please enter your Alpha Vantage API key in the sidebar")
    else:
        api = AlphaVantageAPI(st.session_state.api_key)

        selected_indicator = st.selectbox(
            "Select Indicator",
            options=list(MACRO_INDICATORS.keys()),
            index=0
        )

        if st.button("📊 Load Data", type="primary"):
            indicator_code = MACRO_INDICATORS[selected_indicator]

            with st.spinner(f"Fetching {selected_indicator}..."):
                df_macro = api.get_macro_data(indicator_code)

                if not df_macro.empty:
                    # Latest values
                    latest = df_macro.iloc[-1]
                    previous = df_macro.iloc[-2] if len(df_macro) > 1 else None

                    col1, col2, col3 = st.columns(3)

                    with col1:
                        st.metric("Latest Value", f"{latest['value']:.2f}")
                    with col2:
                        st.metric("Date", latest['date'].strftime('%Y-%m-%d'))
                    with col3:
                        if previous is not None:
                            change = latest['value'] - previous['value']
                            st.metric("Change", f"{change:+.2f}")

                    st.markdown("---")

                    # Trend chart
                    fig = px.line(
                        df_macro.tail(24),
                        x='date',
                        y='value',
                        title=f"{selected_indicator} - 24 Month Trend",
                        markers=True
                    )

                    fig.update_layout(
                        yaxis_title="Value",
                        xaxis_title="Date",
                        height=500
                    )

                    st.plotly_chart(fig, use_container_width=True)

                    # Recent data table
                    st.subheader("📊 Recent Data")
                    st.dataframe(
                        df_macro.tail(10)[['date', 'value']].sort_values('date', ascending=False),
                        use_container_width=True,
                        hide_index=True
                    )
                else:
                    st.error("❌ Failed to fetch macro data")

# ===========================
# TAB 4: PRICE ANALYSIS
# ===========================
with tab4:
    st.header("📈 Stock Comparison")

    if not st.session_state.api_initialized:
        st.warning("⚠️ Please enter your Alpha Vantage API key in the sidebar")
    else:
        api = AlphaVantageAPI(st.session_state.api_key)

        st.markdown("Compare performance of multiple stocks")

        selected_stocks = st.multiselect(
            "Select Stocks to Compare",
            options=list(STOCK_SYMBOLS.keys()),
            default=list(STOCK_SYMBOLS.keys())[:3]
        )

        if st.button("📊 Compare", type="primary") and selected_stocks:
            comparison_data = []

            progress_bar = st.progress(0)

            for i, stock_name in enumerate(selected_stocks):
                symbol = STOCK_SYMBOLS[stock_name]

                with st.spinner(f"Fetching {stock_name}..."):
                    quote = api.get_quote(symbol)

                    if quote:
                        change_pct = float(quote['change_percent'].rstrip('%'))
                        comparison_data.append({
                            'Stock': stock_name,
                            'Price': quote['price'],
                            'Change %': change_pct,
                            'Volume': quote['volume']
                        })

                progress_bar.progress((i + 1) / len(selected_stocks))

            if comparison_data:
                df_comparison = pd.DataFrame(comparison_data)

                # Display table
                st.dataframe(df_comparison, use_container_width=True, hide_index=True)

                # Bar chart
                fig = px.bar(
                    df_comparison,
                    x='Stock',
                    y='Change %',
                    color='Change %',
                    color_continuous_scale=['red', 'yellow', 'green'],
                    title='Stock Performance Comparison',
                    text='Change %'
                )

                fig.update_traces(texttemplate='%{text:.2f}%', textposition='outside')
                fig.update_layout(height=400)

                st.plotly_chart(fig, use_container_width=True)

# ===========================
# FOOTER
# ===========================
st.markdown("---")
st.caption("💡 Market Intelligence Dashboard | Data from Alpha Vantage & Google News")
st.caption("⚠️ Free API tier: 25 requests/day | Rate limited: 12 seconds between requests")